export const values = {
    host : 'the-cocktail-db.p.rapidapi.com',
    imageHost : 'https://spoonacular.com/recipeImages',
    key : '6c44591209msh7c6ddbe65fcf242p19ebe2jsn3a3455db4dee',
    resultsList : '.results__list',
    searchInput : '.search__field',
    searchButton : '.search__btn',
    loader : 'loader',
    cors : 'https://crossorigin.me/',
    limit : 10,
    pageParent : '.results__pages',
    recipe : '.recipe',
    resultListElem : '.results__link',
    ingredientsList : '.recipe__ingredient-list',
    shoppingList : '.shopping__list',
    shoppingItem : '.shopping__item',
    recipeBtn : '.recipe__btn',
    deleteBtn : '.shopping__delete',
    likesList : '.likes__list',
    likeButton : '.recipe__love',
    likeListElem : '.likes__link',
    dataPage : 'data-page',
    imgLiked : 'img/icons.svg#icon-heart',
    imgUnliked : 'img/icons.svg#icon-heart-outlined',
    dataItemId : 'data-item-id'
};
